baseURL = 'https://www.mag.com.au/'
languageCode = 'en-us'
title = 'Melbourne Aviation Group'

theme = ['hugo-embed-pdf-shortcode','tailbliss']
enableInlineShortcodes = true

[markup.goldmark.renderer]
unsafe = true