- name: "Docker Img: Build and push Docker image to ECR"
  import_playbook: docker-playbook.yaml
  tags: [docker]

- name: "VPC: Create network infrastructure"
  import_playbook: vpc-playbook.yaml
  tags: [vpc]

- name: "EKS: Create the EKS Cluster and deploy containers"
  import_playbook: eks-playbook.yaml
  tags: [eks]
